#!/bin/bash

# look at the domain we are on and set up the proxy config in response
DOMAIN=`hostname -d`
if [ "$DOMAIN" = "gc2.dc1.gnm" ]; then
    PROXY_CONF=""
else
    PROXY_CONF="-Dhttp.proxyHost=proxy.gucode.gnl -Dhttp.proxyPort=3128"
fi

cat /dev/null | java -Xmx1G -XX:MaxPermSize=250m \
    -Dsbt.log.noformat=true \
    -Dbuild.number="$BUILD_NUMBER" \
    -Dbuild.vcs.number="$BUILD_VCS_NUMBER" \
    $PROXY_CONF \
    -jar sbt-launch.jar "$@"

